# ─────────────────────────────────────────────────────────────────────
# THIS SCRIPT WAS GENERATED BY ANTHROPIC'S CLAUDE. THIS WAS NOT MADE BY ME!
# Delt-Arcade · Backend API
# File: main.py
#
# WHAT THIS IS:
# A FastAPI application that acts as the middleman between your
# website and MongoDB. It also serves all the HTML frontend files
# directly, so you only need to run one process — no separate web
# server required.
#
# FOLDER STRUCTURE:
#   project/
#   ├── main.py
#   ├── .env
#   ├── assets/          ← logo.png, favicon.png, bg.png, card_*.png
#   ├── login.html
#   ├── register.html
#   ├── dashboard-admin.html
#   ├── dashboard-guest.html
#   └── account.html
#
# SETUP INSTRUCTIONS:
#   1. Install dependencies:
#      pip install fastapi uvicorn pymongo python-jose[cryptography] passlib[bcrypt] python-dotenv bcrypt==4.0.1
#      (if using bcrypt directly instead of passlib: pip install "bcrypt==4.0.1")
#
#   2. Create a .env file in the same directory with:
#      MONGO_URI=mongodb://localhost:27017
#      DB_NAME=delt_arcade
#      SECRET_KEY=your-very-long-random-secret-key-change-this
#      SCANNER_KEY=a-separate-long-secret-for-the-physical-scanner
#
#   3. Run the server:
#      uvicorn main:app --reload
#
#   4. Open your browser to:
#      http://localhost:8000              ← redirects to login
#      http://localhost:8000/docs         ← interactive API docs
#
# ROUTES SUMMARY:
#   Pages:        GET / (redirect), GET /login, GET /register
#                 GET /dashboard-admin, GET /dashboard-guest, GET /account
#   Auth:         POST /auth/register, POST /auth/login, GET /auth/me
#                 GET /auth/me/full, PUT /auth/me
#   Cards:        GET /cards/check-uid/{uid}
#                 POST /cards/add, GET /cards/my-cards, GET /cards/{uid}
#   Card history: GET /cards/{uid}/transactions
#   Credit reqs:  POST /cards/request-credits, GET /cards/my-requests
#   Admin users:  GET /admin/users, GET /admin/pending-users
#                 POST /admin/approve-user/{username}, POST /admin/deny-user/{username}
#   Admin cards:  GET /admin/cards, GET /admin/pending-cards
#                 POST /admin/approve-card, POST /admin/deny-card/{uid}
#                 POST /admin/add-card, POST /admin/add-credits
#                 PUT  /admin/cards/{uid}/design
#                 PUT  /admin/cards/{uid}/owner
#                 DELETE /admin/remove-card/{uid}
#   Admin credits:GET /admin/credit-requests
#                 POST /admin/credit-requests/{uid}/approve
#                 POST /admin/credit-requests/{uid}/deny
#   Admin stats:  GET /admin/stats, GET /admin/transactions
#   News:         GET /news
#                 POST /admin/news, DELETE /admin/news/{post_id}
#   Scanner:      POST /scanner/scan
# ─────────────────────────────────────────────────────────────────────

import os
import uuid
from datetime import datetime, timedelta, timezone
from typing import Optional, List
from pathlib import Path

from fastapi import FastAPI, HTTPException, Depends, status
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse, RedirectResponse
from fastapi.staticfiles import StaticFiles
from fastapi.security import HTTPBearer, HTTPAuthorizationCredentials
from pydantic import BaseModel
from pymongo import MongoClient, DESCENDING
from bson import ObjectId
from passlib.context import CryptContext
from jose import JWTError, jwt
from dotenv import load_dotenv

# Load environment variables from .env file
# WHY: Never hardcode secrets in source code. If this file is ever
# shared or version-controlled, your secrets stay safe.
load_dotenv()

MONGO_URI  = os.getenv("MONGO_URI",  "mongodb://localhost:27017")
DB_NAME    = os.getenv("DB_NAME",    "delt_arcade")
SECRET_KEY = os.getenv("SECRET_KEY", "CHANGE-THIS-IN-PRODUCTION")
ALGORITHM  = "HS256"          # JWT signing algorithm
TOKEN_EXPIRE_HOURS = 8        # Tokens expire after 8 hours

# ── MongoDB connection ──
# MongoClient creates a connection pool automatically.
# We access collections like: db["users"], db["cards"]
client = MongoClient(MONGO_URI)
db     = client[DB_NAME]

# ── Password hashing ──
# WHY bcrypt? It's intentionally slow, which makes brute-force attacks
# expensive. NEVER store plain-text passwords. passlib handles the
# salt generation and hashing automatically.
pwd_ctx = CryptContext(schemes=["bcrypt"], deprecated="auto")

# ── FastAPI app ──
app = FastAPI(
    title="Delt-Arcade API",
    description="Backend API for the Delt-Arcade management system",
    version="1.0.0"
)

# ── CORS Middleware ──
# CORS (Cross-Origin Resource Sharing) is a browser security feature.
# By default, browsers BLOCK your website from calling an API on a
# different domain/port. This middleware tells the browser it's allowed.
# In production, replace "*" with your actual website domain.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],        # TODO: restrict to your domain in prod
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# ── Static assets ──
# Serves everything in the ./assets folder at /assets/...
# e.g. assets/logo.png becomes http://localhost:8000/assets/logo.png
# WHY mount before routes? FastAPI checks mounts before route handlers,
# so /assets/* never accidentally hits an API route.
HERE = Path(__file__).parent   # directory main.py lives in

assets_path = HERE / "assets"
if assets_path.exists():
    app.mount("/assets", StaticFiles(directory=str(assets_path)), name="assets")

css_path = HERE / "css"
if assets_path.exists():
    app.mount("/css", StaticFiles(directory=str(css_path)), name="css")

js_path = HERE / "js"
if assets_path.exists():
    app.mount("/js", StaticFiles(directory=str(js_path)), name="js")
# ── HTML page routes ──
# Each returns the corresponding HTML file from the project folder.
# We use FileResponse which sets the correct Content-Type (text/html)
# and supports browser caching headers automatically.
#
# WHY individual routes instead of a catch-all?
# A catch-all would also swallow requests for missing pages and return
# HTML instead of a 404, which breaks API error handling. Named routes
# are explicit and safe.

def _page(filename: str) -> FileResponse:
    """Return an HTML file from the project directory."""
    path = HERE / filename
    if not path.exists():
        raise HTTPException(status_code=404, detail=f"Page '{filename}' not found")
    return FileResponse(str(path), media_type="text/html")

@app.get("/", include_in_schema=False)
def root_redirect():
    """Visiting the bare root URL redirects to the login page."""
    return RedirectResponse(url="/login")

@app.get("/login", include_in_schema=False)
def page_login():
    return _page("login.html")

@app.get("/register", include_in_schema=False)
def page_register():
    return _page("register.html")

@app.get("/dashboard-admin", include_in_schema=False)
def page_dashboard_admin():
    return _page("dashboard-admin.html")

@app.get("/dashboard-guest", include_in_schema=False)
def page_dashboard_guest():
    return _page("dashboard-guest.html")

@app.get("/account", include_in_schema=False)
def page_account():
    return _page("account.html")

# ── JWT bearer scheme (for protected routes) ──
security = HTTPBearer()


# ─────────────────────────────────────────────
# PYDANTIC MODELS
# WHY: Pydantic validates incoming request data automatically.
# If a required field is missing or the wrong type, FastAPI returns
# a clear 422 error — you don't have to write validation manually.
# ─────────────────────────────────────────────

class LoginRequest(BaseModel):
    username: str
    password: str

class RegisterRequest(BaseModel):
    username: str
    password: str
    email: str
    display_name: str

class TokenResponse(BaseModel):
    access_token: str
    token_type: str = "bearer"
    role: str
    username: str

# ── Card models ──

class AddCardRequest(BaseModel):
    uid: str
    nickname: str
    design: str        # "purple" or "teal"

class AdminAddCardRequest(BaseModel):
    uid: str
    nickname: str
    design: str
    owner_username: Optional[str] = None   # Can be left unassigned
    starting_balance: float = 0.0
    is_service: bool = False               # Service cards bypass debit flow

class ApproveCardRequest(BaseModel):
    uid: str

class AddCreditsRequest(BaseModel):
    uid: str
    amount: float
    note: Optional[str] = None

class ScanRequest(BaseModel):
    uid: str
    amount: float = 0.0   # Not required for service card scans
    note: Optional[str] = None

class UpdateProfileRequest(BaseModel):
    display_name:     Optional[str] = None
    email:            Optional[str] = None
    avatar:           Optional[str] = None  # base64 data URI
    current_password: Optional[str] = None  # required when changing password
    new_password:     Optional[str] = None

class AssignDesignRequest(BaseModel):
    design: str   # "purple" or "teal"

class AssignOwnerRequest(BaseModel):
    owner_username: Optional[str] = None  # None = unassign

class CreditRequestModel(BaseModel):
    uid:    str
    amount: float   # Must match one of the allowed presets

class NewsPostRequest(BaseModel):
    title:  str
    body:   str


# ─────────────────────────────────────────────
# HELPER FUNCTIONS
# ─────────────────────────────────────────────

def hash_password(plain: str) -> str:
    """Hash a plain-text password using bcrypt."""
    return pwd_ctx.hash(plain)

def verify_password(plain: str, hashed: str) -> bool:
    """Check if a plain password matches its stored bcrypt hash."""
    return pwd_ctx.verify(plain, hashed)

def create_access_token(data: dict) -> str:
    """
    Create a signed JWT token.

    HOW IT WORKS:
    - We take a dict (payload) and add an expiry time
    - jose signs it with our SECRET_KEY using HMAC-SHA256
    - The result is a string like: xxxxx.yyyyy.zzzzz
    - Anyone can decode the first two parts (they're base64)
    - But the third part (signature) can only be verified by
      someone who knows the SECRET_KEY
    """
    payload = data.copy()
    expire  = datetime.now(timezone.utc) + timedelta(hours=TOKEN_EXPIRE_HOURS)
    payload.update({"exp": expire})
    return jwt.encode(payload, SECRET_KEY, algorithm=ALGORITHM)

def decode_token(token: str) -> dict:
    """Verify and decode a JWT. Raises an error if invalid or expired."""
    try:
        return jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
    except JWTError:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Invalid or expired token",
            headers={"WWW-Authenticate": "Bearer"},
        )

def get_current_user(credentials: HTTPAuthorizationCredentials = Depends(security)):
    """
    Dependency function — extracts and validates the JWT from the
    Authorization header on any protected route.

    USAGE: Add `user = Depends(get_current_user)` to any route
    that requires authentication. FastAPI runs this automatically.
    """
    return decode_token(credentials.credentials)

def require_admin(user: dict = Depends(get_current_user)):
    """Dependency that additionally enforces the admin role."""
    if user.get("role") != "admin":
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Administrator access required"
        )
    return user

def require_scanner(credentials: HTTPAuthorizationCredentials = Depends(security)):
    """
    Dependency for the scanner endpoint.
    The physical scanner authenticates with a static API key stored
    in the .env file rather than a user JWT. This keeps the scanner
    simple — it never needs to log in, it just sends its key.

    WHY a separate key? The scanner is a hardware device. It can't
    do a login flow. We give it one long-lived secret instead.
    Add SCANNER_KEY=your-scanner-secret to your .env file.
    """
    expected = os.getenv("SCANNER_KEY", "")
    if not expected:
        raise HTTPException(status_code=500, detail="SCANNER_KEY not configured")
    if credentials.credentials != expected:
        raise HTTPException(status_code=401, detail="Invalid scanner key")
    return True

def serialize(doc: dict) -> dict:
    """
    Convert MongoDB ObjectId fields to plain strings so they can
    be returned as JSON. FastAPI can't serialize ObjectId natively.
    We also convert any nested ObjectIds if present.
    """
    doc["_id"] = str(doc["_id"])
    return doc


# ─────────────────────────────────────────────
# ROUTES
# ─────────────────────────────────────────────

# ── POST /auth/register ──
# Guests call this to create a new account.
# Account starts as pending=True until an admin approves it.
@app.post("/auth/register", status_code=201)
def register(req: RegisterRequest):
    # Check username isn't already taken
    if db["users"].find_one({"username": req.username}):
        raise HTTPException(status_code=409, detail="Username already exists")

    # Check email isn't already registered
    if db["users"].find_one({"email": req.email}):
        raise HTTPException(status_code=409, detail="Email already registered")

    # Build the user document to store in MongoDB
    user_doc = {
        "username":     req.username,
        "email":        req.email,
        "display_name": req.display_name,
        "password":     hash_password(req.password),  # NEVER store plain text
        "role":         "guest",
        "approved":     False,   # Must be approved by admin before login
        "created_at":   datetime.now(timezone.utc),
    }

    db["users"].insert_one(user_doc)
    return {"message": "Account created. Please wait for admin approval."}


# ── POST /auth/login ──
# Validates credentials and returns a JWT if successful.
@app.post("/auth/login", response_model=TokenResponse)
def login(req: LoginRequest):
    # Look up the user in MongoDB by username
    user = db["users"].find_one({"username": req.username})

    # WHY do we check password even if user doesn't exist?
    # "Timing attacks" — if we return instantly for unknown users
    # but slowly for wrong passwords, an attacker can enumerate
    # valid usernames. Always do the full check regardless.
    if not user or not verify_password(req.password, user["password"]):
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Incorrect username or password"
        )

    # Guest accounts must be approved by an admin first
    if user["role"] == "guest" and not user.get("approved", False):
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Your account is pending admin approval"
        )

    # Build the JWT payload — this data is accessible on the frontend
    # and the backend without a DB query (that's the power of JWTs)
    token = create_access_token({
        "sub":      str(user["_id"]),   # "sub" = subject (standard JWT claim)
        "username": user["username"],
        "role":     user["role"],
    })

    return TokenResponse(
        access_token=token,
        role=user["role"],
        username=user["username"]
    )


# ── GET /auth/me ──
# Returns the current user's info from their JWT.
@app.get("/auth/me")
def me(user: dict = Depends(get_current_user)):
    return {"username": user["username"], "role": user["role"]}


# ── GET /auth/me/full ──
# Returns the full user document (minus password) for the account page.
@app.get("/auth/me/full")
def me_full(user: dict = Depends(get_current_user)):
    doc = db["users"].find_one(
        {"username": user["username"]},
        {"password": 0}   # Never return the password hash
    )
    if not doc:
        raise HTTPException(status_code=404, detail="User not found")
    doc["_id"] = str(doc["_id"])
    return doc


# ── PUT /auth/me ──
# Updates profile fields for the currently logged-in user.
# All fields are optional — only provided fields are updated.
# Password change requires current_password for verification.
@app.put("/auth/me")
def update_me(req: UpdateProfileRequest, user: dict = Depends(get_current_user)):
    updates = {}

    if req.display_name is not None:
        if len(req.display_name.strip()) < 2:
            raise HTTPException(status_code=400, detail="Display name too short")
        updates["display_name"] = req.display_name.strip()

    if req.email is not None:
        # Check email isn't already taken by a different user
        existing = db["users"].find_one({"email": req.email})
        if existing and existing["username"] != user["username"]:
            raise HTTPException(status_code=409, detail="Email already in use")
        updates["email"] = req.email

    if req.avatar is not None:
        # Basic validation — must start with a data URI prefix
        if not req.avatar.startswith("data:image/"):
            raise HTTPException(status_code=400, detail="Invalid image format")
        # Rough size check: base64 of 2MB file ≈ 2.7MB string ≈ 2,700,000 chars
        if len(req.avatar) > 3_000_000:
            raise HTTPException(status_code=413, detail="Image too large (max 2 MB)")
        updates["avatar"] = req.avatar

    if req.new_password is not None:
        # Password change requires verifying the current password first
        if not req.current_password:
            raise HTTPException(status_code=400, detail="current_password is required")

        doc = db["users"].find_one({"username": user["username"]})
        if not verify_password(req.current_password, doc["password"]):
            raise HTTPException(status_code=401, detail="Current password is incorrect")

        if len(req.new_password) < 8:
            raise HTTPException(status_code=400, detail="New password must be at least 8 characters")

        updates["password"] = hash_password(req.new_password)

    if not updates:
        raise HTTPException(status_code=400, detail="No fields provided to update")

    db["users"].update_one({"username": user["username"]}, {"$set": updates})
    return {"message": "Profile updated successfully"}


# ── GET /admin/pending-users ──
# Admin only: see all guest accounts awaiting approval.
@app.get("/admin/pending-users")
def pending_users(admin: dict = Depends(require_admin)):
    users = list(db["users"].find(
        {"role": "guest", "approved": False},
        {"password": 0}  # Exclude the password field from results
    ))
    # MongoDB _id is a special ObjectId type — convert to string for JSON
    for u in users:
        u["_id"] = str(u["_id"])
    return users


# ── POST /admin/approve-user/{username} ──
# Admin only: approve a pending guest account.
@app.post("/admin/approve-user/{username}")
def approve_user(username: str, admin: dict = Depends(require_admin)):
    result = db["users"].update_one(
        {"username": username, "role": "guest"},
        {"$set": {"approved": True, "denied": False}}
    )
    if result.matched_count == 0:
        raise HTTPException(status_code=404, detail="User not found")
    return {"message": f"User '{username}' has been approved"}


# ── POST /admin/deny-user/{username} ──
# Admin only: deny a guest account without deleting it.
# WHY keep denied records? Audit trail — you can see who applied
# and was rejected, and reverse the decision later if needed.
@app.post("/admin/deny-user/{username}")
def deny_user(username: str, admin: dict = Depends(require_admin)):
    result = db["users"].update_one(
        {"username": username, "role": "guest"},
        {"$set": {"approved": False, "denied": True}}
    )
    if result.matched_count == 0:
        raise HTTPException(status_code=404, detail="User not found")
    return {"message": f"User '{username}' has been denied"}


# ── POST /admin/deny-card/{uid} ──
# Admin only: deny a card request without deleting it.
@app.post("/admin/deny-card/{uid}")
def deny_card(uid: str, admin: dict = Depends(require_admin)):
    uid = uid.upper().strip()
    result = db["cards"].update_one(
        {"uid": uid},
        {"$set": {"approved": False, "denied": True}}
    )
    if result.matched_count == 0:
        raise HTTPException(status_code=404, detail="Card not found")
    return {"message": f"Card '{uid}' has been denied"}


# ── GET /admin/users ──
# Admin only: list ALL guest users (approved, pending, and denied).
# Excludes password field from results for safety.
@app.get("/admin/users")
def all_users(admin: dict = Depends(require_admin)):
    users = list(db["users"].find(
        {"role": "guest"},
        {"password": 0}
    ))
    for u in users:
        u["_id"] = str(u["_id"])
    return users


# ── GET /admin/cards ──
# Admin only: list ALL cards regardless of status.
# Cards with no owner (owner_username is None) are included —
# the frontend checks for null/None rather than UID to show add-card flow.
@app.get("/admin/cards")
def all_cards(admin: dict = Depends(require_admin)):
    cards = list(db["cards"].find({}, {"_id": 0}))
    # Normalise owner_username: convert None to null-safe empty string
    # so the frontend can do a simple truthiness check
    for c in cards:
        if c.get("owner_username") is None:
            c["owner_username"] = None   # Explicit None → JSON null
    return cards


# ── PUT /admin/cards/{uid}/design ──
# Admin assigns or changes the card design (purple / teal).
@app.put("/admin/cards/{uid}/design")
def set_card_design(uid: str, req: AssignDesignRequest, admin: dict = Depends(require_admin)):
    design = req.design.lower().strip()
    if design not in ("purple", "teal"):
        raise HTTPException(status_code=400, detail="Design must be 'purple' or 'teal'")
    uid = uid.upper().strip()
    result = db["cards"].update_one({"uid": uid}, {"$set": {"design": design}})
    if result.matched_count == 0:
        raise HTTPException(status_code=404, detail="Card not found")
    return {"message": f"Card {uid} design set to {design}"}


# ── PUT /admin/cards/{uid}/owner ──
# Admin reassigns or clears the owner of a card.
# Handles malicious/accidental claims — sets owner_username to
# a new user or null (unassigned), updating both the card document
# and the linked_cards arrays on the affected users.
@app.put("/admin/cards/{uid}/owner")
def set_card_owner(uid: str, req: AssignOwnerRequest, admin: dict = Depends(require_admin)):
    uid       = uid.upper().strip()
    new_owner = req.owner_username  # None means unassign

    card = db["cards"].find_one({"uid": uid})
    if not card:
        raise HTTPException(status_code=404, detail="Card not found")

    if card.get("is_service"):
        raise HTTPException(status_code=400, detail="Service cards cannot be assigned to a user")

    old_owner = card.get("owner_username")

    # Validate new owner exists if provided
    if new_owner:
        user = db["users"].find_one({"username": new_owner})
        if not user:
            raise HTTPException(status_code=404, detail="User not found")

    # Remove UID from old owner's linked_cards
    if old_owner:
        db["users"].update_one(
            {"username": old_owner},
            {"$pull": {"linked_cards": uid}}
        )

    # Add UID to new owner's linked_cards
    if new_owner:
        db["users"].update_one(
            {"username": new_owner},
            {"$addToSet": {"linked_cards": uid}}
        )

    db["cards"].update_one(
        {"uid": uid},
        {"$set": {"owner_username": new_owner or None}}
    )

    msg = f"Card {uid} assigned to '{new_owner}'" if new_owner else f"Card {uid} owner cleared"
    return {"message": msg}


# ── POST /admin/add-card ──
# Admin adds a card directly — bypasses the approval flow.
# Optionally assigns an owner and sets a starting balance.
# Service cards (is_service=True) bypass all debit logic at the scanner.
@app.post("/admin/add-card", status_code=201)
def admin_add_card(req: AdminAddCardRequest, admin: dict = Depends(require_admin)):
    # Service cards now also accept a design value
    if not req.is_service and req.design not in ("purple", "teal"):
        raise HTTPException(status_code=400, detail="Design must be 'purple' or 'teal'")

    uid = req.uid.upper().strip()

    if db["cards"].find_one({"uid": uid}):
        raise HTTPException(status_code=409, detail="A card with this UID already exists")

    # Service cards cannot be assigned to a guest user
    if req.is_service and req.owner_username:
        raise HTTPException(status_code=400, detail="Service cards cannot be assigned to a user")

    # Validate owner if provided (regular cards only)
    if req.owner_username:
        owner = db["users"].find_one({"username": req.owner_username})
        if not owner:
            raise HTTPException(status_code=404, detail="Owner username not found")

    card_doc = {
        "uid":            uid,
        "nickname":       req.nickname,
        "design":         req.design,  # Admin picks design for all card types
        "balance":        0.0 if req.is_service else round(req.starting_balance, 2),
        "owner_username": None,   # Service cards are never user-owned
        "approved":       True,
        "denied":         False,
        "is_service":     req.is_service,
        "created_at":     datetime.now(timezone.utc),
        "last_used":      None,
    }

    db["cards"].insert_one(card_doc)

    # Link to owner's account if provided (regular cards only)
    if req.owner_username and not req.is_service:
        card_doc["owner_username"] = req.owner_username
        db["cards"].update_one({"uid": uid}, {"$set": {"owner_username": req.owner_username}})
        db["users"].update_one(
            {"username": req.owner_username},
            {"$addToSet": {"linked_cards": uid}}
        )

    # Starting balance transaction (regular cards only)
    if not req.is_service and req.starting_balance > 0:
        db["transactions"].insert_one({
            "card_uid":       uid,
            "owner_username": req.owner_username or "unassigned",
            "type":           "credit",
            "amount":         round(req.starting_balance, 2),
            "balance_before": 0.0,
            "balance_after":  round(req.starting_balance, 2),
            "source":         "admin",
            "note":           f"Starting balance set by admin ({admin['username']})",
            "timestamp":      datetime.now(timezone.utc),
        })

    card_type = "Service card" if req.is_service else "Card"
    return {"message": f"{card_type} '{uid}' created successfully.", "uid": uid}


# ─────────────────────────────────────────────
# CARD ROUTES
# ─────────────────────────────────────────────

# ── GET /cards/check-uid/{uid} ──
# Returns whether a UID is available for a guest to claim.
# A UID is only available if it already exists in the database
# AND has no owner yet — meaning an admin pre-registered it.
# UIDs not in the database at all are rejected; all cards must
# be set up by an administrator before guests can claim them.
@app.get("/cards/check-uid/{uid}")
def check_uid(uid: str, user: dict = Depends(get_current_user)):
    uid = uid.upper().strip()
    card = db["cards"].find_one({"uid": uid})

    if card is None:
        # Not in the system — admin hasn't registered this card yet
        return {"uid": uid, "available": False, "status": "unknown"}

    if card.get("is_service"):
        # Service cards can never be claimed by guests
        return {"uid": uid, "available": False, "status": "service"}

    if card.get("owner_username") is None:
        # Exists and unowned — guest can claim it
        return {"uid": uid, "available": True, "status": "unowned"}

    # Already owned by someone
    return {"uid": uid, "available": False, "status": "owned"}


# ── POST /cards/add ──
# Guest claims a pre-registered card that has no owner yet.
# Cards must be set up by an administrator first — guests cannot
# create new card records, only claim existing unowned ones.
@app.post("/cards/add", status_code=201)
def add_card(req: AddCardRequest, user: dict = Depends(get_current_user)):
    uid = req.uid.upper().strip()

    existing = db["cards"].find_one({"uid": uid})

    if existing is None:
        raise HTTPException(
            status_code=404,
            detail="This card UID is not registered in the system. Contact an administrator."
        )

    if existing.get("owner_username") is not None:
        raise HTTPException(
            status_code=409,
            detail="This card is already registered to another user."
        )

    # Unowned card — claim it
    db["cards"].update_one(
        {"uid": uid},
        {"$set": {
            "owner_username": user["username"],
            "nickname":       req.nickname,
        }}
    )
    db["users"].update_one(
        {"username": user["username"]},
        {"$addToSet": {"linked_cards": uid}}
    )

    return {"message": "Card claimed successfully.", "uid": uid}


# ── GET /cards/my-cards ──
# Returns all cards linked to the currently logged-in user.
@app.get("/cards/my-cards")
def my_cards(user: dict = Depends(get_current_user)):
    cards = list(db["cards"].find(
        {"owner_username": user["username"]},
        {"_id": 0}
    ))
    return cards


# ── POST /cards/{uid}/release ──
# Guest removes a card from their account.
# Does NOT delete the card — it stays in the database with its
# balance and transaction history intact, but owner_username is
# cleared so the admin can reassign it or the guest can reclaim it.
# WHY not a DELETE? DELETE implies destroying the record permanently.
# We only want to disassociate the guest from it.
@app.post("/cards/{uid}/release")
def release_card(uid: str, user: dict = Depends(get_current_user)):
    uid  = uid.upper().strip()
    card = db["cards"].find_one({"uid": uid})

    if not card:
        raise HTTPException(status_code=404, detail="Card not found")

    # Guests can only release their own cards
    if card.get("owner_username") != user["username"]:
        raise HTTPException(status_code=403, detail="This card does not belong to your account")

    # Clear the owner and remove the UID from the user's linked_cards list
    db["cards"].update_one(
        {"uid": uid},
        {"$set": {"owner_username": None, "nickname": "Delt-Arcade Game Card"}}
    )
    db["users"].update_one(
        {"username": user["username"]},
        {"$pull": {"linked_cards": uid}}
    )

    return {"message": f"Card '{uid}' removed from your account."}


# ── GET /cards/{uid} ──
# Fetch a single card by UID. Guests can only see their own cards;
# admins can see any card.
@app.get("/cards/{uid}")
def get_card(uid: str, user: dict = Depends(get_current_user)):
    uid = uid.upper().strip()
    card = db["cards"].find_one({"uid": uid}, {"_id": 0})

    if not card:
        raise HTTPException(status_code=404, detail="Card not found")

    # Guests are blocked from viewing cards they don't own
    if user["role"] != "admin" and card["owner_username"] != user["username"]:
        raise HTTPException(status_code=403, detail="Access denied")

    return card


# ─────────────────────────────────────────────
# ADMIN — CARD MANAGEMENT ROUTES
# ─────────────────────────────────────────────

# ── POST /admin/add-credits ──
# Admin manually adds credits to a card (e.g. purchase, reward).
# This creates a transaction record for full auditability.
@app.post("/admin/add-credits")
def add_credits(req: AddCreditsRequest, admin: dict = Depends(require_admin)):
    if req.amount <= 0:
        raise HTTPException(status_code=400, detail="Amount must be greater than zero")

    uid = req.uid.upper().strip()
    card = db["cards"].find_one({"uid": uid})
    if not card:
        raise HTTPException(status_code=404, detail="Card not found")
    if not card["approved"]:
        raise HTTPException(status_code=400, detail="Card is not yet approved")

    balance_before = card["balance"]
    balance_after  = round(balance_before + req.amount, 2)

    # Update the card balance
    db["cards"].update_one(
        {"uid": uid},
        {"$set": {"balance": balance_after}}
    )

    # Write a transaction record
    # WHY record balance_before and balance_after?
    # So you can audit or reconstruct history without recalculating.
    # If a bug ever corrupts a balance, you have a complete paper trail.
    db["transactions"].insert_one({
        "card_uid":       uid,
        "owner_username": card["owner_username"],
        "type":           "credit",
        "amount":         req.amount,
        "balance_before": balance_before,
        "balance_after":  balance_after,
        "source":         "admin",
        "note":           req.note or f"Credits added by admin ({admin['username']})",
        "timestamp":      datetime.now(timezone.utc),
    })

    return {
        "message":        f"{req.amount} credits added to card '{uid}'",
        "balance_before": balance_before,
        "balance_after":  balance_after,
    }


# ── DELETE /admin/remove-card/{uid} ──
# Admin permanently removes a card from the system.
# Transactions are kept for audit history.
@app.delete("/admin/remove-card/{uid}")
def remove_card(uid: str, admin: dict = Depends(require_admin)):
    uid = uid.upper().strip()
    card = db["cards"].find_one({"uid": uid})
    if not card:
        raise HTTPException(status_code=404, detail="Card not found")

    # Remove the UID from the owner's linked_cards array
    db["users"].update_one(
        {"username": card["owner_username"]},
        {"$pull": {"linked_cards": uid}}
    )

    db["cards"].delete_one({"uid": uid})
    return {"message": f"Card '{uid}' removed"}


# ─────────────────────────────────────────────
# TRANSACTION ROUTES
# ─────────────────────────────────────────────

# ── GET /cards/{uid}/transactions ──
# Returns transaction history for a card, newest first.
# Guests can only view their own cards' history.
# Optional query param: ?limit=20 (default 50)
@app.get("/cards/{uid}/transactions")
def card_transactions(
    uid: str,
    limit: int = 50,
    user: dict = Depends(get_current_user)
):
    uid  = uid.upper().strip()
    card = db["cards"].find_one({"uid": uid}, {"_id": 0})

    if not card:
        raise HTTPException(status_code=404, detail="Card not found")

    if user["role"] != "admin" and card["owner_username"] != user["username"]:
        raise HTTPException(status_code=403, detail="Access denied")

    # DESCENDING on timestamp = newest first
    # limit() caps how many records we return — protects against
    # returning thousands of rows for very active cards
    txns = list(
        db["transactions"]
        .find({"card_uid": uid}, {"_id": 0})
        .sort("timestamp", DESCENDING)
        .limit(max(1, min(limit, 200)))  # Clamp between 1 and 200
    )
    return txns


# ── GET /admin/transactions ──
# Admin only: view all transactions across all cards.
# Supports optional filters: ?card_uid=X&username=Y&type=debit&limit=100
@app.get("/admin/transactions")
def all_transactions(
    card_uid:  Optional[str] = None,
    username:  Optional[str] = None,
    txn_type:  Optional[str] = None,   # "credit" or "debit"
    limit:     int = 100,
    admin:     dict = Depends(require_admin)
):
    # Build the query filter dynamically based on which params were provided.
    # WHY? We want one flexible endpoint rather than separate endpoints for
    # every combination of filters.
    query = {}
    if card_uid:  query["card_uid"]       = card_uid.upper().strip()
    if username:  query["owner_username"] = username
    if txn_type:  query["type"]           = txn_type

    txns = list(
        db["transactions"]
        .find(query, {"_id": 0})
        .sort("timestamp", DESCENDING)
        .limit(max(1, min(limit, 500)))
    )
    return txns


# ── GET /admin/stats ──
# Admin only: summary statistics for the dashboard overview panel.
# Returns totals that are fast to compute without heavy aggregation.
@app.get("/admin/stats")
def stats(admin: dict = Depends(require_admin)):
    total_users      = db["users"].count_documents({"role": "guest"})
    approved_users   = db["users"].count_documents({"role": "guest", "approved": True})
    pending_users    = db["users"].count_documents({"role": "guest", "approved": False})
    total_cards      = db["cards"].count_documents({})
    approved_cards   = db["cards"].count_documents({"approved": True})
    pending_cards    = db["cards"].count_documents({"approved": False})
    total_txns       = db["transactions"].count_documents({})

    # Sum of all credits ever added across all cards
    # WHY use aggregation here? MongoDB's $sum is done server-side —
    # much faster than pulling all records into Python and summing.
    credit_pipeline = [
        {"$match": {"type": "credit"}},
        {"$group": {"_id": None, "total": {"$sum": "$amount"}}}
    ]
    credit_result = list(db["transactions"].aggregate(credit_pipeline))
    total_credits_added = credit_result[0]["total"] if credit_result else 0

    debit_pipeline = [
        {"$match": {"type": "debit"}},
        {"$group": {"_id": None, "total": {"$sum": "$amount"}}}
    ]
    debit_result = list(db["transactions"].aggregate(debit_pipeline))
    total_credits_spent = debit_result[0]["total"] if debit_result else 0

    return {
        "users": {
            "total":    total_users,
            "approved": approved_users,
            "pending":  pending_users,
        },
        "cards": {
            "total":    total_cards,
            "approved": approved_cards,
            "pending":  pending_cards,
        },
        "transactions": {
            "total":         total_txns,
            "credits_added": round(total_credits_added, 2),
            "credits_spent": round(total_credits_spent, 2),
        }
    }


# ─────────────────────────────────────────────
# SCANNER ROUTE
# ─────────────────────────────────────────────

# ── POST /scanner/scan ──
# Called by the physical card scanner when a card is tapped.
# Authenticated with a static SCANNER_KEY from .env, not a JWT.
#
# SERVICE CARDS:
#   Skip balance check + debit entirely. Log a "service" transaction
#   so there's an audit trail of when the card was used, but no credits
#   are touched. The scanner receives a distinct response so it can
#   trigger a different action (e.g. unlock a service panel).
#
# REGULAR CARDS:
#   Standard debit flow — check balance, debit, write transaction.
@app.post("/scanner/scan")
def scanner_scan(req: ScanRequest, _: bool = Depends(require_scanner)):
    uid  = req.uid.upper().strip()
    card = db["cards"].find_one({"uid": uid})

    if not card:
        raise HTTPException(status_code=404, detail="Card not found")

    if not card.get("approved"):
        raise HTTPException(status_code=403, detail="Card is not activated")

    # ── SERVICE CARD PATH ──
    if card.get("is_service"):
        # Log the scan for audit purposes but don't touch any balance
        db["transactions"].insert_one({
            "card_uid":       uid,
            "owner_username": "service",
            "type":           "service",
            "amount":         0,
            "balance_before": 0,
            "balance_after":  0,
            "source":         "scanner",
            "note":           req.note or "Service card scan",
            "timestamp":      datetime.now(timezone.utc),
        })
        db["cards"].update_one(
            {"uid": uid},
            {"$set": {"last_used": datetime.now(timezone.utc)}}
        )
        # Return a distinct response so the scanner knows it's a service card
        return {
            "success":    True,
            "uid":        uid,
            "is_service": True,
            "message":    f"Service card accepted — {card['nickname']}",
        }

    # ── REGULAR CARD PATH ──
    if req.amount <= 0:
        raise HTTPException(status_code=400, detail="Scan amount must be greater than zero")

    if card["balance"] < req.amount:
        raise HTTPException(
            status_code=402,
            detail=f"Insufficient balance. Current: {card['balance']}, Required: {req.amount}"
        )

    balance_before = card["balance"]
    balance_after  = round(balance_before - req.amount, 2)

    db["cards"].update_one(
        {"uid": uid},
        {"$set": {
            "balance":   balance_after,
            "last_used": datetime.now(timezone.utc)
        }}
    )

    db["transactions"].insert_one({
        "card_uid":       uid,
        "owner_username": card["owner_username"],
        "type":           "debit",
        "amount":         req.amount,
        "balance_before": balance_before,
        "balance_after":  balance_after,
        "source":         "scanner",
        "note":           req.note or "Card scan",
        "timestamp":      datetime.now(timezone.utc),
    })

    return {
        "success":        True,
        "uid":            uid,
        "is_service":     False,
        "balance_before": balance_before,
        "balance_after":  balance_after,
        "owner":          card["owner_username"],
    }


# ─────────────────────────────────────────────
# CREDIT REQUEST ROUTES
# ─────────────────────────────────────────────

ALLOWED_CREDIT_AMOUNTS = {10, 25, 50, 100}

# ── POST /cards/request-credits ──
# Guest submits a request for a preset credit amount.
# Stored in the credit_requests collection; admin approves or denies.
@app.post("/cards/request-credits", status_code=201)
def request_credits(req: CreditRequestModel, user: dict = Depends(get_current_user)):
    if req.amount not in ALLOWED_CREDIT_AMOUNTS:
        raise HTTPException(
            status_code=400,
            detail=f"Amount must be one of: {sorted(ALLOWED_CREDIT_AMOUNTS)}"
        )

    uid  = req.uid.upper().strip()
    card = db["cards"].find_one({"uid": uid})

    if not card:
        raise HTTPException(status_code=404, detail="Card not found")

    # Guests can only request credits for their own cards
    if card["owner_username"] != user["username"]:
        raise HTTPException(status_code=403, detail="Access denied")

    if not card.get("approved"):
        raise HTTPException(status_code=400, detail="Card is not active")

    # Check for an already-pending request on this card
    # WHY? Prevents duplicate submissions if the user clicks twice.
    existing = db["credit_requests"].find_one({
        "card_uid": uid,
        "status":   "pending"
    })
    if existing:
        raise HTTPException(
            status_code=409,
            detail="A credit request for this card is already pending"
        )

    db["credit_requests"].insert_one({
        "card_uid":       uid,
        "owner_username": user["username"],
        "amount":         req.amount,
        "status":         "pending",   # pending | approved | denied
        "requested_at":   datetime.now(timezone.utc),
        "resolved_at":    None,
        "resolved_by":    None,
    })

    return {"message": f"Request for {req.amount} credits submitted for approval."}


# ── GET /cards/my-requests ──
# Guest views their own credit request history.
@app.get("/cards/my-requests")
def my_credit_requests(user: dict = Depends(get_current_user)):
    requests = list(
        db["credit_requests"]
        .find({"owner_username": user["username"]}, {"_id": 0})
        .sort("requested_at", DESCENDING)
        .limit(50)
    )
    return requests


# ── GET /admin/credit-requests ──
# Admin views all pending credit requests.
@app.get("/admin/credit-requests")
def all_credit_requests(
    status: Optional[str] = "pending",
    admin:  dict = Depends(require_admin)
):
    query = {}
    if status: query["status"] = status
    requests = list(
        db["credit_requests"]
        .find(query, {"_id": 0})
        .sort("requested_at", DESCENDING)
        .limit(200)
    )
    return requests


# ── POST /admin/credit-requests/{card_uid}/approve ──
# Admin approves a pending credit request.
# Adds the credits to the card and writes a transaction record.
@app.post("/admin/credit-requests/{card_uid}/approve")
def approve_credit_request(card_uid: str, admin: dict = Depends(require_admin)):
    uid = card_uid.upper().strip()

    req = db["credit_requests"].find_one({"card_uid": uid, "status": "pending"})
    if not req:
        raise HTTPException(status_code=404, detail="No pending request found for this card")

    card = db["cards"].find_one({"uid": uid})
    if not card:
        raise HTTPException(status_code=404, detail="Card not found")

    balance_before = card["balance"]
    balance_after  = round(balance_before + req["amount"], 2)

    db["cards"].update_one({"uid": uid}, {"$set": {"balance": balance_after}})

    db["transactions"].insert_one({
        "card_uid":       uid,
        "owner_username": req["owner_username"],
        "type":           "credit",
        "amount":         req["amount"],
        "balance_before": balance_before,
        "balance_after":  balance_after,
        "source":         "admin",
        "note":           f"Credit request approved by {admin['username']}",
        "timestamp":      datetime.now(timezone.utc),
    })

    db["credit_requests"].update_one(
        {"card_uid": uid, "status": "pending"},
        {"$set": {
            "status":      "approved",
            "resolved_at": datetime.now(timezone.utc),
            "resolved_by": admin["username"],
        }}
    )

    return {"message": f"{req['amount']} credits added to card {uid}", "balance_after": balance_after}


# ── POST /admin/credit-requests/{card_uid}/deny ──
# Admin denies a pending credit request.
@app.post("/admin/credit-requests/{card_uid}/deny")
def deny_credit_request(card_uid: str, admin: dict = Depends(require_admin)):
    uid = card_uid.upper().strip()

    result = db["credit_requests"].update_one(
        {"card_uid": uid, "status": "pending"},
        {"$set": {
            "status":      "denied",
            "resolved_at": datetime.now(timezone.utc),
            "resolved_by": admin["username"],
        }}
    )
    if result.matched_count == 0:
        raise HTTPException(status_code=404, detail="No pending request found for this card")

    return {"message": f"Credit request for card {uid} denied"}


# ─────────────────────────────────────────────
# NEWS ROUTES
# ─────────────────────────────────────────────

# ── GET /news ──
# Public — any logged-in user can read the news feed.
# Returns posts newest first, limited to 20.
@app.get("/news")
def get_news(user: dict = Depends(get_current_user)):
    posts = list(
        db["news"]
        .find({}, {"_id": 0})
        .sort("posted_at", DESCENDING)
        .limit(20)
    )
    return posts


# ── POST /admin/news ──
# Admin creates a news post.
@app.post("/admin/news", status_code=201)
def create_news(req: NewsPostRequest, admin: dict = Depends(require_admin)):
    if not req.title.strip():
        raise HTTPException(status_code=400, detail="Title cannot be empty")
    if not req.body.strip():
        raise HTTPException(status_code=400, detail="Body cannot be empty")

    post = {
        "post_id":   str(uuid.uuid4()),   # Stable ID for deletion
        "title":     req.title.strip(),
        "body":      req.body.strip(),
        "author":    admin["username"],
        "posted_at": datetime.now(timezone.utc),
    }
    db["news"].insert_one(post)
    post["_id"] = str(post.pop("_id", ""))
    return post


# ── DELETE /admin/news/{post_id} ──
# Admin deletes a news post by its post_id.
@app.delete("/admin/news/{post_id}")
def delete_news(post_id: str, admin: dict = Depends(require_admin)):
    result = db["news"].delete_one({"post_id": post_id})
    if result.deleted_count == 0:
        raise HTTPException(status_code=404, detail="Post not found")
    return {"message": "Post deleted"}


# ─────────────────────────────────────────────
# DATABASE SETUP HELPER
# Run this once to create an initial admin account:
#   python -c "from main import create_admin; create_admin()"
# ─────────────────────────────────────────────

def create_admin(username="admin", password="changeme123"):
    """
    One-time script to seed an admin user.
    Run from the command line, then change the password immediately.
    """
    if db["users"].find_one({"username": username}):
        print(f"Admin user '{username}' already exists.")
        return
    db["users"].insert_one({
        "username":     username,
        "email":        "admin@delt-arcade.local",
        "display_name": "Administrator",
        "password":     hash_password(password),
        "role":         "admin",
        "approved":     True,
        "created_at":   datetime.now(timezone.utc),
    })
    print(f"Admin user '{username}' created. Password: {password}")
    print("IMPORTANT: Change this password immediately after first login!")
